services:
  - type: pserv
    name: backend
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GROQ_API_KEY
        sync: false

  - type: web
    name: frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
